/**
 * Emit a dependency-free .NET 8 client for one certified connector.
 *
 * The generated package is deliberately a client of the guarded REST facade,
 * not a second implementation of the adapter or trust engine. Before every
 * operation it checks the facade manifest against the app, certificate version,
 * spec hash, and exact certified operation set compiled into the package.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { BirthCertificate, ConnectorSpec, JsonSchema, OperationSpec } from "../core/types.js";

export interface DotnetPackage {
  directoryName: string;
  files: Record<string, string>;
}

export interface DotnetOptions {
  namespace?: string;
}

export function generateDotnetPackage(
  spec: ConnectorSpec,
  cert: BirthCertificate,
  opts: DotnetOptions = {},
): DotnetPackage {
  if (cert.app !== spec.app || cert.specHash !== spec.specHash) {
    throw new Error("certificate identity does not match the connector spec");
  }

  const byId = new Map(spec.operations.map((op) => [op.id, op]));
  const certified = [...cert.certifiedOps].sort();
  const operations = certified.map((id) => {
    const op = byId.get(id);
    if (!op) throw new Error(`certificate names unknown operation "${id}"`);
    return op;
  });

  const appName = pascal(spec.app) || "Connector";
  const namespace = opts.namespace ? namespaceName(opts.namespace) : `Bridgesmith.Connectors.${appName}`;
  const projectName = `${appName}.Bridgesmith`;
  const models = new ModelEmitter();
  const operationBlocks = operations.map((op) => emitOperation(op, models));
  const modelSource = models.render();
  const expectedOps = certified.map((id) => `        ${csString(id)},`).join("\n");

  const source = `// <auto-generated by Bridgesmith; do not edit>
#nullable enable
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ${namespace};

public sealed class ${appName}Client
{
    public const string CertifiedApp = ${csString(spec.app)};
    public const int CertificateVersion = ${cert.version};
    public const string CertifiedSpecHash = ${csString(spec.specHash)};

    private static readonly string[] CertifiedOperations =
    [
${expectedOps}
    ];

    private readonly HttpClient _http;
    private readonly Uri _baseUri;
    private readonly string? _apiKey;

    public ${appName}Client(HttpClient http, Uri facadeBaseUri, string? apiKey = null)
    {
        _http = http ?? throw new ArgumentNullException(nameof(http));
        ArgumentNullException.ThrowIfNull(facadeBaseUri);
        if (!facadeBaseUri.IsAbsoluteUri) throw new ArgumentException("Facade URI must be absolute.", nameof(facadeBaseUri));
        _baseUri = new Uri(facadeBaseUri.AbsoluteUri.TrimEnd('/') + "/");
        _apiKey = apiKey;
    }

${operationBlocks.join("\n\n")}

    private async Task EnsureCertifiedIdentityAsync(CancellationToken cancellationToken)
    {
        using var response = await _http.GetAsync(new Uri(_baseUri, "manifest"), cancellationToken).ConfigureAwait(false);
        response.EnsureSuccessStatusCode();
        var manifest = await response.Content.ReadFromJsonAsync<BridgesmithManifest>(cancellationToken: cancellationToken).ConfigureAwait(false)
            ?? throw new BridgesmithException("Facade returned an empty manifest.");
        var actualOps = manifest.CertifiedOps.Order(StringComparer.Ordinal).ToArray();
        if (!StringComparer.Ordinal.Equals(manifest.App, CertifiedApp)
            || manifest.Version != CertificateVersion
            || !StringComparer.Ordinal.Equals(manifest.SpecHash, CertifiedSpecHash)
            || !actualOps.SequenceEqual(CertifiedOperations, StringComparer.Ordinal))
        {
            throw new BridgesmithException("Facade identity does not match this certified client package.");
        }
    }

    private async Task<T> CallAsync<T>(string operation, Dictionary<string, object?> parameters, CancellationToken cancellationToken)
    {
        await EnsureCertifiedIdentityAsync(cancellationToken).ConfigureAwait(false);
        using var request = new HttpRequestMessage(HttpMethod.Post, new Uri(_baseUri, $"op/{Uri.EscapeDataString(operation)}"))
        {
            Content = JsonContent.Create(parameters),
        };
        if (_apiKey is not null) request.Headers.Add("x-bridgesmith-key", _apiKey);
        using var response = await _http.SendAsync(request, cancellationToken).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            var detail = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
            throw new BridgesmithException($"Bridgesmith operation {operation} failed with {(int)response.StatusCode}: {detail}");
        }
        var envelope = await response.Content.ReadFromJsonAsync<BridgesmithEnvelope<T>>(cancellationToken: cancellationToken).ConfigureAwait(false)
            ?? throw new BridgesmithException($"Bridgesmith operation {operation} returned an empty response.");
        if (!envelope.Ok) throw new BridgesmithException($"Bridgesmith operation {operation} was refused.");
        return envelope.Data;
    }
}

public sealed class BridgesmithException(string message) : Exception(message);

internal sealed record BridgesmithManifest
{
    [JsonPropertyName("app")]
    public required string App { get; init; }

    [JsonPropertyName("version")]
    public required int Version { get; init; }

    [JsonPropertyName("specHash")]
    public required string SpecHash { get; init; }

    [JsonPropertyName("certifiedOps")]
    public required string[] CertifiedOps { get; init; }
}

internal sealed record BridgesmithEnvelope<T>
{
    [JsonPropertyName("ok")]
    public required bool Ok { get; init; }

    [JsonPropertyName("data")]
    public T Data { get; init; } = default!;
}

${modelSource}
`;

  const project = `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <PackageId>Bridgesmith.Connectors.${appName}</PackageId>
    <Version>0.${cert.version}.0</Version>
    <Description>Certified ${xml(spec.app)} client generated by Bridgesmith.</Description>
  </PropertyGroup>
</Project>
`;

  return {
    directoryName: projectName,
    files: {
      [`${projectName}.csproj`]: project,
      [`${appName}Client.cs`]: source,
    },
  };
}

export function writeDotnetPackage(root: string, generated: DotnetPackage): string {
  const out = join(root, generated.directoryName);
  mkdirSync(out, { recursive: true });
  for (const [name, contents] of Object.entries(generated.files)) {
    writeFileSync(join(out, name), contents);
  }
  return out;
}

function emitOperation(op: OperationSpec, models: ModelEmitter): string {
  const name = pascal(op.id);
  const responseType = models.typeFor(op.responseSchema, `${name}Response`, true);
  const params = [...op.pathParams, ...op.queryParams.map((q) => q.name)];
  const hasBody = op.requestBodySchema !== undefined;
  const requestType = params.length > 0 || hasBody ? `${name}Request` : null;

  if (requestType) {
    const required = new Set([
      ...op.pathParams,
      ...op.queryParams.filter((q) => q.required).map((q) => q.name),
    ]);
    const properties = params.map((p) => property(p, "string", required.has(p)));
    if (op.requestBodySchema) {
      const bodyType = models.typeFor(op.requestBodySchema, `${name}Body`, true);
      properties.push(property("body", bodyType, true));
    }
    models.add(requestType, properties);
  }

  const signature = requestType
    ? `public async Task<${responseType}> ${name}Async(${requestType} request, CancellationToken cancellationToken = default)`
    : `public async Task<${responseType}> ${name}Async(CancellationToken cancellationToken = default)`;
  const payload = requestType
    ? [
      "        ArgumentNullException.ThrowIfNull(request);",
      "        var parameters = new Dictionary<string, object?>();",
      ...params.map((p) => `        if (request.${pascal(p)} is not null) parameters[${csString(p)}] = request.${pascal(p)};`),
      ...(hasBody ? ["        parameters[\"body\"] = request.Body;"] : []),
    ].join("\n")
    : "        var parameters = new Dictionary<string, object?>();";

  return `    ${signature}
    {
${payload}
        return await CallAsync<${responseType}>(${csString(op.id)}, parameters, cancellationToken).ConfigureAwait(false);
    }`;
}

class ModelEmitter {
  private readonly definitions = new Map<string, string[]>();

  add(name: string, properties: string[]): void {
    if (!this.definitions.has(name)) this.definitions.set(name, properties);
  }

  typeFor(schema: JsonSchema, suggestedName: string, required: boolean): string {
    const types = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
    const nullable = schema.nullable === true || types.includes("null") || !required;
    const kind = types.find((t) => t !== "null") ?? (schema.properties ? "object" : "unknown");
    let type: string;
    switch (kind) {
      case "string": type = "string"; break;
      case "integer": type = "long"; break;
      case "number": type = "double"; break;
      case "boolean": type = "bool"; break;
      case "array": {
        const item = this.typeFor(schema.items ?? {}, `${suggestedName}Item`, true);
        type = `IReadOnlyList<${item}>`;
        break;
      }
      case "object": {
        type = suggestedName;
        const requiredNames = new Set(schema.required ?? []);
        const props = Object.entries(schema.properties ?? {})
          .sort(([a], [b]) => a.localeCompare(b))
          .map(([jsonName, child]) => property(
            jsonName,
            this.typeFor(child, `${suggestedName}${pascal(jsonName)}`, requiredNames.has(jsonName)),
            requiredNames.has(jsonName),
            true,
          ));
        this.add(suggestedName, props);
        break;
      }
      default: type = "JsonElement";
    }
    return nullable && !type.endsWith("?") ? `${type}?` : type;
  }

  render(): string {
    return [...this.definitions.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, props]) => `public sealed record ${name}\n{\n${props.join("\n\n")}\n}`)
      .join("\n\n");
  }
}

function property(jsonName: string, type: string, required: boolean, typeAlreadyNullable = false): string {
  const finalType = required || typeAlreadyNullable || type.endsWith("?") ? type : `${type}?`;
  const initializer = required && isReferenceType(finalType) ? " = default!;" : "";
  return `    [JsonPropertyName(${csString(jsonName)})]\n    public ${required ? "required " : ""}${finalType} ${pascal(jsonName)} { get; init; }${initializer}`;
}

function isReferenceType(type: string): boolean {
  return type === "string" || type.startsWith("IReadOnlyList<") || /^[A-Z]/.test(type);
}

function pascal(value: string): string {
  const pieces = value.replace(/[^a-zA-Z0-9]+/g, " ").trim().split(/\s+/).filter(Boolean);
  let out = pieces.map((p) => p[0]!.toUpperCase() + p.slice(1)).join("");
  if (/^\d/.test(out)) out = `_${out}`;
  return out;
}

function namespaceName(value: string): string {
  return value.split(".").map((part) => pascal(part) || "Connector").join(".");
}

function csString(value: string): string {
  return JSON.stringify(value).replace(/\\u2028|\\u2029/g, "");
}

function xml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}
